name: Deploy to EuroDNS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- если у вас есть сборка:
      # - name: Install dependencies
      #   run: npm ci
      #
      # - name: Build
      #   run: npm run build
      # -------------------------------------

      - name: Deploy via FTPS-Implicit to EuroDNS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}         # обычно 990 для implicit FTPS
          protocol: ftps # ftps-implicit
          secure: true
          passive: true
          # если вы собираете в папку dist/, поставьте ./dist/
          local-dir: ./
          server-dir: /httpdocs/
          dangerous-clean-slate: false
          exclude: |
            **/.git/**         # полностью исключаем Git-метаданные
            **/.github/**      # CI-файлы
            node_modules/
            *.log
